site_name: Python Pest
site_description: A general purpose parser written in Python.
site_url: https://jg-rp.github.io/python-pest/

theme:
  name: "material"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      primary: "purple"
      accent: "purple"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: purple
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
  features:
    - navigation.sections
    - content.code.copy

repo_name: jg-rp/python-pest
repo_url: https://github.com/jg-rp/python-pest
edit_uri: ""

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            separate_signature: true
            docstring_section_style: "spacy"
  - autorefs

nav:
  - Introduction: "index.md"
  - Overview: "overview.md"
  - API: "api.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
